name: lpp
on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        rosdistro: ['noetic']
        gcc: ['8', '9', '10']
        cxx: ['11', '14', '17']
    container: ros:${{ matrix.rosdistro }}-ros-base-focal
    name: ROS ${{ matrix.rosdistro }} - GCC ${{ matrix.gcc }}
    steps:
    - uses: actions/checkout@v3
      name: Checkout lpp
      with:
        repository: ethz-asl/lpp
        token: ${{ secrets.PAT }}
        path: catkin_ws/src/lpp

    - name: Install newest git version
      run: sudo apt update && sudo apt-get install -y software-properties-common && sudo add-apt-repository -y ppa:git-core/ppa && sudo apt-get update && sudo apt-get install -y git

    - name: Install GCC version ${{ matrix.gcc }}
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y && sudo apt update && sudo apt install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }} && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc }} 100 --slave /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.gcc }}

    - name: Install catkin tools
      run: sudo apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential python3-catkin-tools

    - name: Install system dependencies
      run: sudo apt install -y libgoogle-glog-dev

    - name: Build lpp
      run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash && catkin build -DCMAKE_CXX_STANDARD=${{ matrix.cxx }} lpp && source ${GITHUB_WORKSPACE}/catkin_ws/devel/setup.bash
      working-directory: catkin_ws
      shell: bash

    - name: Run unittests
      run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash && source ${GITHUB_WORKSPACE}/catkin_ws/devel/setup.bash && rosrun lpp test_lpp && rosrun lpp test_glog && rosrun lpp test_lpp_custom && rosrun lpp test_nolog && rosrun lpp test_default && rosrun lpp test_roslog
      working-directory: catkin_ws
      shell: bash
